version: '3.4'
services:
  redis:
    image: redis
    container_name: redis
#    command: redis-server /usr/local/etc/redis/redis.conf
    command: redis-server
    volumes:
       - /etc/redis:/usr/local/etc/redis
       - /etc/data:/data
#      - C:\Users\growth\redis_volume\redis.conf:/usr/local/etc/redis/redis.conf
#      - C:\Users\growth\redis_volume\data:/data
    restart: always

  springboot:
    image: growth123/ticket
    container_name: springboot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
